uuvir corn orders.app/;   p?:app     :app --reload[?1l>[?2004l
]2;uvicorn orders.app:app --reload]1;uvicorn[32mINFO[0m:     Will watch for changes in these directories: ['/Users/corikomiyama/Desktop/coffee-mesh-project/ch02']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m5214[0m] using [36m[1mStatReload[0m
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 31
    def create_order(order_details: CreateOrderSchema):
IndentationError: unexpected indent
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 19, in <module>
    class OrderItemSchema(BaseModel):   # Every pydantic model inherits from pydantic's BaseModel
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 22, in OrderItemSchema
    quantity: Optional[conint(ge=1, strict=True)] = 1   # We specify quantity's minimum value and we give it a default
              ^^^^^^^^
NameError: name 'Optional' is not defined
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 19, in <module>
    class OrderItemSchema(BaseModel):   # Every pydantic model inherits from pydantic's BaseModel
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 22, in OrderItemSchema
    quantity: optional[conint(ge=1, strict=True)] = 1   # We specify quantity's minimum value and we give it a default
              ^^^^^^^^
NameError: name 'optional' is not defined
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 19, in <module>
    class OrderItemSchema(BaseModel):   # Every pydantic model inherits from pydantic's BaseModel
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 22, in OrderItemSchema
    quantity: Optional[conint(ge=1, strict=True)] = 1   # We specify quantity's minimum value and we give it a default
              ^^^^^^^^
NameError: name 'Optional' is not defined
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 24, in <module>
    class CreateOrderSchema(BaseModel):
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 25, in CreateOrderSchema
    order: conlist(OrderItemSchema, min_items=1)    # We use pydantic's conlist type to define a list with at least one element
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: conlist() got an unexpected keyword argument 'min_items'
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 24, in <module>
    class CreateOrderSchema(BaseModel):
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 25, in CreateOrderSchema
    order: conlist(OrderItemSchema, min_items=1)    # We use pydantic's conlist type to define a list with at least one element
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: conlist() got an unexpected keyword argument 'min_items'
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 19, in <module>
    class OrderItemSchema(BaseModel):   # Every pydantic model inherits from pydantic's BaseModel
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 22, in OrderItemSchema
    quantity: Optional[conint(ge=1, strict=True)] = 1   # We specify quantity's minimum value and we give it a default
              ^^^^^^^^
NameError: name 'Optional' is not defined
clear
^C[32mINFO[0m:     Stopping reloader process [[36m[1m5214[0m]
[1m[7m%[27m[1m[0m                                                                                                                                                            ]2;corikomiyama@coris-mbp:~/desktop/coffee-mesh-project/ch02]1;..-project/ch02]7;file://coris-mbp.dhcp.asu.edu/Users/corikomiyama/desktop/coffee-mesh-project/ch02\[0m[27m[24m[J(ch02) [01;32m➜  [36mch02[00m [01;34mgit:([31mmain[34m) [33m✗[00m [K[?1h=[?2004hcclear[?1l>[?2004l
]2;clear]1;clear[H[2J[1m[7m%[27m[1m[0m                                                                                                                                                            ]2;corikomiyama@coris-mbp:~/desktop/coffee-mesh-project/ch02]1;..-project/ch02]7;file://coris-mbp.dhcp.asu.edu/Users/corikomiyama/desktop/coffee-mesh-project/ch02\[0m[27m[24m[J(ch02) [01;32m➜  [36mch02[00m [01;34mgit:([31mmain[34m) [33m✗[00m [K[?1h=[?2004h[0m[27m[24m[J(ch02) [01;32m➜  [36mch02[00m [01;34mgit:([31mmain[34m) [33m✗[00m [0m[27m[24m[J(ch02) [01;32m➜  [36mch02[00m [01;34mgit:([31mmain[34m) [33m✗[00m uuvicorn orders.app:app --reload[?1l>[?2004l
]2;uvicorn orders.app:app --reload]1;uvicorn[32mINFO[0m:     Will watch for changes in these directories: ['/Users/corikomiyama/Desktop/coffee-mesh-project/ch02']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m5341[0m] using [36m[1mStatReload[0m
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 24, in <module>
    class CreateOrderSchema(BaseModel):
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 25, in CreateOrderSchema
    order: conlist(OrderItemSchema, min_items=1)    # We use pydantic's conlist type to define a list with at least one element
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: conlist() got an unexpected keyword argument 'min_items'
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 27, in <module>
    class GetOrderSchema(CreateOrderSchema):
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 29, in GetOrderSchema
    created: datetime
             ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
[32mINFO[0m:     Started server process [[36m5382[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50607 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50607 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5382[0m]
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 40
    'body'
    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 40
    'body'
    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/app.py", line 5, in <module>
    from orders.api import api
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 8, in <module>
    from orders.api.schemas import CreateOrderSchema # We import the pydantic models so we can use them for validation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/schemas.py", line 40
    'body'
    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
[32mINFO[0m:     Started server process [[36m5475[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50619 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50620 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50620 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5475[0m]
[32mINFO[0m:     Started server process [[36m5487[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5487[0m]
[32mINFO[0m:     Started server process [[36m5493[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50626 - "[1mGET /orders HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 27, in get_orders
    return {'orders': [orders]}
                       ^^^^^^
NameError: name 'orders' is not defined. Did you mean: 'order'?
[32mINFO[0m:     127.0.0.1:50628 - "[1mGET /orders HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/corikomiyama/.local/share/virtualenvs/ch02-5ME4VFfE/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corikomiyama/Desktop/coffee-mesh-project/ch02/orders/api/api.py", line 27, in get_orders
    return {'orders': [orders]}
                       ^^^^^^
NameError: name 'orders' is not defined. Did you mean: 'order'?
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5493[0m]
[32mINFO[0m:     Started server process [[36m5506[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5506[0m]
[32mINFO[0m:     Started server process [[36m5524[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/schemas.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5524[0m]
[32mINFO[0m:     Started server process [[36m5540[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5540[0m]
[32mINFO[0m:     Started server process [[36m5549[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5549[0m]
[32mINFO[0m:     Started server process [[36m5560[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5560[0m]
[32mINFO[0m:     Started server process [[36m5566[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5566[0m]
[32mINFO[0m:     Started server process [[36m5570[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50635 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50635 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5570[0m]
[32mINFO[0m:     Started server process [[36m5584[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5584[0m]
[32mINFO[0m:     Started server process [[36m5590[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50643 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50643 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
[33mWARNING[0m:  StatReload detected changes in 'orders/api/api.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5590[0m]
[32mINFO[0m:     Started server process [[36m5597[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:50647 - "[1mPOST /orders HTTP/1.1[0m" [31m422 Unprocessable Entity[0m
